// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"github.com/tal-tech/go-zero/rest"
	"github.com/zhuxinlei/micro_book/book/cmd/api/internal/svc"
	"net/http"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/search/book",
				Handler: search_bookHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/search/user",
				Handler: search_userHandler(serverCtx),
			},
		},
	)
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/book",
				Handler: bookHandler(serverCtx),
			},
		},
	)
}
