// Code generated by goctl. DO NOT EDIT!
// Source: book.proto

package server

import (
	"context"

	"github.com/zhuxinlei/micro_book/book/cmd/rpc/book"
	"github.com/zhuxinlei/micro_book/book/cmd/rpc/internal/logic"
	"github.com/zhuxinlei/micro_book/book/cmd/rpc/internal/svc"
)

type BookServer struct {
	svcCtx *svc.ServiceContext
}

func NewBookServer(svcCtx *svc.ServiceContext) *BookServer {
	return &BookServer{
		svcCtx: svcCtx,
	}
}

func (s *BookServer) GetBook(ctx context.Context, in *book.IdReq) (*book.BookInfoReply, error) {
	l := logic.NewGetBookLogic(ctx, s.svcCtx)
	return l.GetBook(in)
}

func (s *BookServer) Test(ctx context.Context, in *book.IdReq) (*book.BookInfoReply, error) {
	l := logic.NewTestLogic(ctx, s.svcCtx)
	return l.Test(in)
}

func (s *BookServer) GetBooks(ctx context.Context, in *book.IdsReq) (*book.BookInfosReply, error) {
	l := logic.NewGetBooksLogic(ctx, s.svcCtx)
	return l.GetBooks(in)
}
