// Code generated by goctl. DO NOT EDIT.
package types

type Reply struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type SearchBookReq struct {
	BookID int64 `json:"book_id"`
}

type SearchUserReq struct {
	UserName string `json:"user_name"`
}
