// Code generated by goctl. DO NOT EDIT.
package types

import (
	"github.com/jinzhu/gorm"
	"github.com/shopspring/decimal"
	"time"
)

type Reply struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type SearchBookReq struct {
	BookName string `json:"book_name"`
}

type SearchUserReq struct {
	UserName string `json:"user_name"`
}

type InsertBookReq struct {
	gorm.Model
	BookName    string          `json:"book_name"`
	Price       decimal.Decimal `json:"price"`
	Author      string          `json:"author"`
	PublishTime time.Time       `json:"publish_time"`
	Desc        string          `json:"desc"`
}
